version: '3.1'

services:

  db:
    image: mysql    
    environment:
      MYSQL_ROOT_PASSWORD: 'mySql2019'
    
    ports:
      - "3306:3306"
   
# version: '3'

# services:
#   mysqlsrv:
#     image: mysql:5.7  
#     environment:
#       MYSQL_DATABASE: 'db'
#       # So you don't have to use root, but you can if you like
#       MYSQL_USER: 'user'
#       # You can use whatever password you like
#       MYSQL_PASSWORD: 'mySql2019'
#       # Password for root access
#       MYSQL_ROOT_PASSWORD: 'mySql2019'
    
#     ports:
#       - "3306:3306"
#    # volumes:
#     #  - Users\jorge\OneDrive\Documentos\Docker\volumes

